version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development    
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    depends_on:
      - postgres
    command: npm run start:dev
    ports:
      - 3000:3000  
    networks:
      - postgres 

  postgres:
    container_name: postgres           
    image: postgres:latest
    ports:
      - "5430:5432"    
    volumes:
      - postgres_api_data:/data/postgres   
    env_file:
      - docker.env  
    networks:
      - postgres
  
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin_api_data:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
  
  redis:
    container_name: redis
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"

  redis-commander:
    container_name: rediscommander
    image: rediscommander/redis-commander:latest    
    env_file:
      - docker.env
    ports:
      - "8081:8081"
    depends_on:
        - redis

volumes:
  postgres_api_data: {}
  pgadmin_api_data: {}

networks:
  postgres:
    driver: bridge